services:
  broker:
    image:
      rabbitmq:management
    container_name: 'broker'
    restart: no
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  cache:
    image:
      redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  email:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    depends_on:
      broker:
        condition: service_healthy
    restart: always
    environment:
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - RABBIT_HOST=broker
    networks:
      - mynetwork

  logging:
    build:
      context: ./logging-service
      dockerfile: Dockerfile
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - RABBIT_HOST=broker
    networks:
      - mynetwork
    volumes:
      - ./logs:/app/logs

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    depends_on:
      broker:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      - RABBIT_HOST=broker
      - REDIS_HOST=cache
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
